name: vedicjivan

services:
  vedicjivan-api:
    build: .
    container_name: vedicjivan-api
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - vedicjivan-mongo
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  vedicjivan-mongo:
    image: mongo:7
    container_name: vedicjivan-mongo
    ports:
      - "27017:27017"
    volumes:
      - vedicjivan_mongo_data:/data/db
    restart: unless-stopped

volumes:
  vedicjivan_mongo_data:
